package com.juxin.predestinate.bean.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.juxin.predestinate.bean.cache.CacheEntity;
import com.juxin.predestinate.bean.center.User;

import com.juxin.predestinate.bean.db.CacheEntityDao;
import com.juxin.predestinate.bean.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheEntityDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CacheEntityDao cacheEntityDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheEntityDaoConfig = daoConfigMap.get(CacheEntityDao.class).clone();
        cacheEntityDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        cacheEntityDao = new CacheEntityDao(cacheEntityDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(CacheEntity.class, cacheEntityDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        cacheEntityDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CacheEntityDao getCacheEntityDao() {
        return cacheEntityDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
